"""Thinking Robot Labs: authenticated loopback Arduino compiler and serial helper."""
import argparse
import codecs
import json
import re
import secrets
import shutil
import subprocess
import tempfile
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse

import serial
from serial.tools import list_ports

FQBNS = {
    "uno": "arduino:avr:uno",
    "nano": "arduino:avr:nano:cpu=atmega328",
    "mega": "arduino:avr:mega:cpu=atmega2560",
}


class Problem(Exception):
    def __init__(self, message, status=400):
        super().__init__(message)
        self.status = status


def validate_upload(data):
    board = data.get("board")
    if board not in FQBNS:
        raise Problem("Choose Arduino Uno, Nano or Mega.")
    code = data.get("code")
    if not isinstance(code, str) or not code or len(code.encode("utf-8")) > 100_000:
        raise Problem("Sketch must contain 1–100,000 bytes.")
    if not code.startswith("// Made with Thinking Robot Labs\n#include <Arduino.h>\n"):
        raise Problem("Upload a sketch generated by Labs.")
    # Compiler directives can read arbitrary local files. Only the generated include is allowed.
    for line in code.splitlines():
        if re.match(r"\s*#", line) and line.strip() != "#include <Arduino.h>":
            raise Problem("Only the standard Arduino header is supported.")
    if "\\\n" in code or "??/" in code or "/*" in code or "*/" in code:
        raise Problem("Unsupported source syntax.")
    fqbn = FQBNS[board]
    if board == "nano" and data.get("oldNano") is True:
        fqbn = "arduino:avr:nano:cpu=atmega328old"
    return code, fqbn


class BoardSession:
    def __init__(self):
        self.lock = threading.RLock()
        self.operation = threading.Lock()
        self.port = None
        self.device = None
        self.uploading = False
        self.decoder = codecs.getincrementaldecoder("utf-8")(errors="replace")

    @staticmethod
    def check_port(device):
        if not isinstance(device, str) or device not in {p.device for p in list_ports.comports()}:
            raise Problem("This USB port is no longer available. Refresh local ports.")
        return device

    def close(self):
        with self.lock:
            if self.port:
                self.port.close()
            self.port = None
            self.device = None

    def connect(self, device):
        device = self.check_port(device)
        with self.lock:
            self.close()
            self.port = serial.Serial(device, baudrate=115200, timeout=0, write_timeout=2)
            self.device = device
            self.decoder.reset()

    def monitor(self):
        with self.lock:
            if self.uploading:
                return {"connected": True, "text": "", "uploading": True}
            if not self.port:
                return {"connected": False, "text": ""}
            try:
                text = self.decoder.decode(self.port.read(min(self.port.in_waiting, 65536)))
                return {"connected": True, "text": text}
            except (serial.SerialException, OSError):
                self.close()
                return {"connected": False, "text": "\nUSB connection lost.\n"}

    def send(self, text):
        if not isinstance(text, str) or len(text) > 1024:
            raise Problem("Serial message must be at most 1024 characters.")
        with self.lock:
            if not self.port or self.uploading:
                raise Problem("Connect a board and wait for upload to finish.", 409)
            self.port.write(text.encode("utf-8"))

    def upload(self, data):
        code, fqbn = validate_upload(data)
        device = self.check_port(data.get("port"))
        cli = shutil.which("arduino-cli")
        if not cli:
            raise Problem("Install Arduino CLI on PATH, then run arduino-cli core install arduino:avr.")
        with self.lock:
            if self.device != device or not self.port:
                raise Problem("Connect the selected port before uploading.", 409)
            self.close()
            self.uploading = True
        output = []
        try:
            with tempfile.TemporaryDirectory(prefix="labs-sketch-") as folder:
                sketch = Path(folder) / "labs_sketch"
                sketch.mkdir()
                (sketch / "labs_sketch.ino").write_text(code, encoding="utf-8")
                build = Path(folder) / "build"
                commands = [
                    [cli, "compile", "--fqbn", fqbn, "--build-path", str(build), str(sketch)],
                    [cli, "upload", "--fqbn", fqbn, "--port", device, "--input-dir", str(build), str(sketch)],
                ]
                for command in commands:
                    result = subprocess.run(command, capture_output=True, text=True, errors="replace", timeout=75, shell=False)
                    output.append((result.stdout + result.stderr)[-30000:])
                    if result.returncode:
                        raise Problem("Compile/upload failed:\n" + "\n".join(output), 422)
            return {"log": "\n".join(output)}
        except subprocess.TimeoutExpired as exc:
            raise Problem("Arduino CLI timed out. Check your port, installed AVR core and cable.", 504) from exc
        finally:
            with self.lock:
                try:
                    self.connect(device)
                except (Problem, serial.SerialException, OSError):
                    self.close()
                self.uploading = False


def make_handler(session, token, origins):
    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *_args):
            pass  # Never log bearer tokens, code, or serial data.

        def origin_allowed(self):
            origin = self.headers.get("Origin")
            return origin is None or origin in origins

        def host_allowed(self):
            return self.headers.get("Host") in {"127.0.0.1:8765", "localhost:8765"}

        def respond(self, data, status=200):
            encoded = json.dumps(data).encode()
            self.send_response(status)
            origin = self.headers.get("Origin")
            if origin in origins:
                self.send_header("Access-Control-Allow-Origin", origin)
            self.send_header("Vary", "Origin")
            self.send_header("Cache-Control", "no-store")
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(encoded)))
            self.end_headers()
            self.wfile.write(encoded)

        def do_OPTIONS(self):
            if not self.host_allowed() or not self.origin_allowed():
                return self.respond({"error": "Origin or host not allowed."}, 403)
            self.send_response(204)
            origin = self.headers.get("Origin")
            if origin in origins:
                self.send_header("Access-Control-Allow-Origin", origin)
            self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
            self.send_header("Access-Control-Allow-Headers", "Authorization, Content-Type")
            self.send_header("Access-Control-Allow-Private-Network", "true")
            self.send_header("Vary", "Origin")
            self.send_header("Content-Length", "0")
            self.end_headers()

        def authorized(self):
            if not self.host_allowed() or not self.origin_allowed():
                self.respond({"error": "Origin or host not allowed. Start helper with --origin matching the Labs URL."}, 403)
                return False
            if not secrets.compare_digest(self.headers.get("Authorization", ""), "Bearer " + token):
                self.respond({"error": "Invalid helper token. Paste the token printed in your terminal."}, 401)
                return False
            return True

        def do_GET(self):
            if not self.authorized():
                return
            if self.path == "/ports":
                self.respond({"ports": [{"device": p.device, "description": p.description} for p in list_ports.comports()], "arduinoCli": bool(shutil.which("arduino-cli"))})
            elif self.path == "/monitor":
                self.respond(session.monitor())
            else:
                self.respond({"error": "Unknown route."}, 404)

        def do_POST(self):
            if not self.authorized():
                return
            if not session.operation.acquire(blocking=False):
                return self.respond({"error": "A board operation is in progress. Wait for it to finish."}, 409)
            try:
                size = int(self.headers.get("Content-Length", "0"))
                if not 0 < size <= 200000:
                    raise Problem("Request body must be under 200 KB.", 413)
                self.connection.settimeout(10)
                data = json.loads(self.rfile.read(size))
                if not isinstance(data, dict):
                    raise Problem("Expected a JSON object.")
                if self.path == "/connect":
                    session.connect(data.get("port"))
                    self.respond({"connected": True})
                elif self.path == "/disconnect":
                    session.close()
                    self.respond({"connected": False})
                elif self.path == "/send":
                    session.send(data.get("text"))
                    self.respond({"ok": True})
                elif self.path == "/upload":
                    self.respond(session.upload(data))
                else:
                    self.respond({"error": "Unknown route."}, 404)
            except Problem as exc:
                self.respond({"error": str(exc)}, exc.status)
            except (ValueError, serial.SerialException, OSError) as exc:
                self.respond({"error": str(exc)}, 400)
            finally:
                session.operation.release()

    return Handler


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--origin", action="append", required=True, help="Exact Labs origin, e.g. http://localhost:3000. Repeat for additional origins.")
    args = parser.parse_args()
    for origin in args.origin:
        parsed = urlparse(origin)
        if parsed.scheme not in {"http", "https"} or not parsed.netloc or parsed.path or parsed.query or parsed.fragment or parsed.username:
            parser.error("Each --origin must be a scheme and hostname (optional port), without a trailing slash or path.")
    token = secrets.token_urlsafe(32)
    session = BoardSession()
    server = ThreadingHTTPServer(("127.0.0.1", 8765), make_handler(session, token, set(args.origin)))
    server.daemon_threads = True
    print("Thinking Robot Labs helper: http://127.0.0.1:8765", flush=True)
    print("Allowed origins: " + ", ".join(args.origin), flush=True)
    print("Temporary token: " + token, flush=True)
    print("Keep this terminal open. Ctrl+C to stop. Arduino CLI: " + (shutil.which("arduino-cli") or "NOT FOUND"), flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopping helper.")
    finally:
        server.server_close()
        session.close()


if __name__ == "__main__":
    main()
